timeout: 5
retry: 2
max_log_days: 30
services:
  - name: "我的NAS"
    api:
      - url: "https://luckyoubest.synology.me:5001"
      - url: "https://luckyoubest.synology.me:21"
      - url: "https://luckyoubest.synology.me:84"
      - url: "https://luckyoubest.synology.me:32400"
      - url: "https://luckyoubest.synology.me:5230"
